# Generated by Django 4.0.6 on 2022-07-30 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentations', '0003_presentation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentation')),
            ],
        ),
    ]
