# Generated by Django 4.0.6 on 2022-08-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationslot',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
