# Generated by Django 4.0.6 on 2022-07-29 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import presentations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='embed_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=presentations.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
