# Generated by Django 4.0.6 on 2022-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presentations", "0002_alter_presentation_embed_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
